import { PlatformUser } from "./userTypes";

export const INITIAL_USERS: PlatformUser[] = [
  {
    id: "usr-001",
    name: "Mahmudur Rahman",
    email: "owner@rahmanfashion.com",
    phone: "+880 1711-234567",
    role: "owner",
    organization: "Rahman Fashion Ltd.",
    organizationId: "org-01",
    status: "active",
    lastLogin: "10 mins ago",
    twoFactorEnabled: true,
  },
  {
    id: "usr-002",
    name: "Kamrul Islam",
    email: "kamrul@rahmanfashion.com",
    phone: "+880 1819-345678",
    role: "manager",
    organization: "Rahman Fashion Ltd.",
    organizationId: "org-01",
    status: "active",
    lastLogin: "2 hours ago",
    twoFactorEnabled: false,
  },
  {
    id: "usr-003",
    name: "Nurul Huda",
    email: "nurul@noorgrocery.com",
    phone: "+880 1912-987654",
    role: "owner",
    organization: "Noor Grocery & Super Shop",
    organizationId: "org-02",
    status: "active",
    lastLogin: "1 day ago",
    twoFactorEnabled: true,
  },
  {
    id: "usr-004",
    name: "Farhana Akter",
    email: "cashier1@noorgrocery.com",
    phone: "+880 1622-456789",
    role: "cashier",
    organization: "Noor Grocery & Super Shop",
    organizationId: "org-02",
    status: "active",
    lastLogin: "Just now",
    twoFactorEnabled: false,
  },
  {
    id: "usr-005",
    name: "Syed Rafiqul Islam",
    email: "rafiq@sylhetelec.com",
    phone: "+880 1715-678901",
    role: "owner",
    organization: "Sylhet Electronics Hub",
    organizationId: "org-03",
    status: "active",
    lastLogin: "3 days ago",
    twoFactorEnabled: true,
  },
  {
    id: "usr-006",
    name: "Tariqul Anam",
    email: "tariqul@greenpharmacy.com",
    phone: "+880 1822-112233",
    role: "owner",
    organization: "Green Pharmacy & Surgicals",
    organizationId: "org-04",
    status: "suspended",
    lastLogin: "2 weeks ago",
    twoFactorEnabled: false,
  },
  {
    id: "usr-007",
    name: "System Security Lead",
    email: "security@xyzbusinessos.com",
    phone: "+880 1700-000001",
    role: "super_admin",
    organization: "XYZ Business OS Platform",
    organizationId: "platform",
    status: "active",
    lastLogin: "Just now",
    twoFactorEnabled: true,
  },
];
