export const tailwindColors = {
  background: "hsl(var(--background))",
  foreground: "hsl(var(--foreground))",
  card: {
    DEFAULT: "hsl(var(--card))",
    foreground: "hsl(var(--card-foreground))",
  },
  popover: {
    DEFAULT: "hsl(var(--popover))",
    foreground: "hsl(var(--popover-foreground))",
  },
  primary: {
    DEFAULT: "hsl(var(--primary))",
    foreground: "hsl(var(--primary-foreground))",
    hover: "hsl(var(--primary-hover))",
    soft: "hsl(var(--primary-soft))",
    50: "#eef2ff",
    100: "#e0e7ff",
    200: "#c7d2fe",
    300: "#a5b4fc",
    400: "#818cf8",
    500: "#6366f1",
    600: "#4f46e5",
    700: "#4338ca",
    800: "#3730a3",
    900: "#312e81",
    950: "#1e1b4b",
  },
  secondary: {
    DEFAULT: "hsl(var(--secondary))",
    foreground: "hsl(var(--secondary-foreground))",
  },
  muted: {
    DEFAULT: "hsl(var(--muted))",
    foreground: "hsl(var(--muted-foreground))",
  },
  accent: {
    DEFAULT: "hsl(var(--accent))",
    foreground: "hsl(var(--accent-foreground))",
    soft: "hsl(var(--accent-soft))",
    blue: "#2563eb",
    "blue-soft": "#eff6ff",
  },
  destructive: {
    DEFAULT: "hsl(var(--destructive))",
    foreground: "hsl(var(--destructive-foreground))",
    soft: "hsl(var(--destructive-soft))",
    50: "#fef2f2",
    600: "#dc2626",
    700: "#b91c1c",
  },
  border: {
    DEFAULT: "hsl(var(--border))",
    strong: "hsl(var(--border-strong))",
  },
  input: "hsl(var(--input))",
  ring: "hsl(var(--ring))",
  success: {
    DEFAULT: "hsl(var(--success))",
    soft: "hsl(var(--success-soft))",
    50: "#f0fdf4",
    100: "#dcfce7",
    500: "#22c55e",
    600: "#16a34a",
    700: "#15803d",
  },
  warning: {
    DEFAULT: "hsl(var(--warning))",
    soft: "hsl(var(--warning-soft))",
    50: "#fffbeb",
    100: "#fef3c7",
    500: "#f59e0b",
    600: "#d97706",
    700: "#b45309",
  },
  info: {
    DEFAULT: "hsl(var(--info))",
    soft: "hsl(var(--info-soft))",
    50: "#f0f9ff",
    100: "#e0f2fe",
    500: "#0ea5e9",
    600: "#0284c7",
    700: "#0369a1",
  },
};
