import React from "react";
import Link from "next/link";
import { JournalEntry } from "@/lib/types";
import { formatCurrency, formatDate } from "@/lib/utils";
import { ArrowRight } from "lucide-react";

interface RecentJournalPostingsProps {
  journals: JournalEntry[];
}

export function RecentJournalPostings({ journals }: RecentJournalPostingsProps) {
  return (
    <div className="rounded-3xl border border-border/80 bg-card p-5 space-y-4 shadow-subtle-sm">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-bold text-sm sm:text-base text-foreground tracking-tight">
            Recent Automated Journal Postings
          </h3>
          <p className="text-xs text-muted-foreground">
            Real-time debit/credit records generated by POS and operations
          </p>
        </div>
        <Link
          href="/app/accounting/journal"
          className="text-xs font-semibold text-indigo-600 dark:text-indigo-400 hover:underline flex items-center gap-1"
        >
          <span>View Full General Ledger</span>
          <ArrowRight className="h-3 w-3" />
        </Link>
      </div>

      <div className="overflow-x-auto rounded-2xl border border-border/60">
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b border-border/80 bg-muted/40 text-[11px] font-bold text-muted-foreground uppercase tracking-wider">
              <th className="p-3.5">Entry Number</th>
              <th className="p-3.5">Date</th>
              <th className="p-3.5">Description</th>
              <th className="p-3.5">Debit (DR)</th>
              <th className="p-3.5">Credit (CR)</th>
              <th className="p-3.5 text-right">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border/60 bg-card">
            {journals.slice(0, 4).map((j) => {
              const totalDebit = j.lines.reduce((sum, l) => sum + (l.debit || 0), 0);
              const totalCredit = j.lines.reduce((sum, l) => sum + (l.credit || 0), 0);
              return (
                <tr key={j.id} className="hover:bg-muted/30 transition-colors">
                  <td className="p-3.5 font-mono font-bold text-blue-600 dark:text-blue-400">
                    {j.entryNumber}
                  </td>
                  <td className="p-3.5 text-muted-foreground font-mono">
                    {formatDate(j.date)}
                  </td>
                  <td className="p-3.5 text-foreground font-medium">
                    {j.description}
                  </td>
                  <td className="p-3.5 font-mono font-bold text-foreground">
                    {formatCurrency(totalDebit)}
                  </td>
                  <td className="p-3.5 font-mono font-bold text-foreground">
                    {formatCurrency(totalCredit)}
                  </td>
                  <td className="p-3.5 text-right">
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                      Balanced
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
