import {
  ShoppingCart,
  Boxes,
  Truck,
  Building,
  BookOpen,
  CreditCard,
  Users,
  CalendarCheck,
  Banknote,
} from "lucide-react";

export const CORE_MODULES = [
  {
    number: 1,
    icon: ShoppingCart,
    title: "Offline-First POS",
    desc: "Blazing-fast point of sale terminal that works completely without internet via Dexie.js IndexedDB. Multi-payment support, thermal receipt printing, and quick SKU/Barcode scanning.",
    category: "Sales & Checkout",
  },
  {
    number: 2,
    icon: Boxes,
    title: "Real-Time Inventory & Warehouses",
    desc: "Tracks stock levels across all branches with minimum stock warning alerts, cost/selling price tracking, and batch/expiry dates.",
    category: "Inventory & Operations",
  },
  {
    number: 3,
    icon: Truck,
    title: "Inter-Branch Stock Transfers",
    desc: "Seamlessly dispatch and receive goods between outlets with approval status workflows and permanent audit history.",
    category: "Inventory & Operations",
  },
  {
    number: 4,
    icon: Building,
    title: "Multi-Branch Operations",
    desc: "Manage multiple retail outlets, departmental floors, and warehouse hubs under one single tenant account with branch-level permissions.",
    category: "Inventory & Operations",
  },
  {
    number: 5,
    icon: BookOpen,
    title: "Automated Double-Entry Accounting",
    desc: "Every POS sale, purchase, and payroll run automatically posts debit and credit journal entries to your Chart of Accounts.",
    category: "Finance & Accounting",
  },
  {
    number: 6,
    icon: CreditCard,
    title: "Cash & Bank Management",
    desc: "Manage Cash in Hand, bKash Merchant, Nagad, Rocket, and corporate bank accounts with live balance reconciliation.",
    category: "Finance & Accounting",
  },
  {
    number: 7,
    icon: Users,
    title: "Employee Directory & HR",
    desc: "Maintain complete employee files with designations, base salaries, sales commission rates, and branch assignments.",
    category: "HR & Payroll",
  },
  {
    number: 8,
    icon: CalendarCheck,
    title: "Daily Attendance & Leave",
    desc: "Daily staff check-in/out logs with status monitoring (Present, Late, Absent, On Leave) and leave approval workflows.",
    category: "HR & Payroll",
  },
  {
    number: 9,
    icon: Banknote,
    title: "Monthly Payroll & Payslips",
    desc: "One-click payroll run calculation that accounts for deductions, calculates earned sales commissions, and generates employee payslips in BDT.",
    category: "HR & Payroll",
  },
];